### ISSUE TITLE
Preview calendar

### ISSUE THREAD

**Issue by chule143** [facelessuser/QuickCal#4]
When I open calendar, the calendar is moved on the left in line of the number of the week:

![calendar-issue](https://cloud.githubusercontent.com/assets/1250071/10212113/ceb37b86-67c8-11e5-85c7-7d56f72c08cd.PNG)

My font config are:
"font_face": "Ubuntu",
"font_size": 10,

**Comment by facelessuser** [comment]
I imagine you are going to need to use a monospaced font.

**Comment by facelessuser** [comment]
Was your question answered?

**Comment by chule143** [comment]
Generally I use the Ubuntu font in my ST3, but i'll gonna use monospaced font for this plugin :)
